version: '3'

tasks:
  test:
    desc: run the test
    cmds:
    - go test -v -cover ./...
  server:
    desc: init the server
    cmds:
      - go run cmd/api/main.go
  api_doc:
    desc: generate swagger documentation
    cmds:
      - swag init -g cmd/api/main.go