DROP TABLE IF EXISTS short_link CASCADE;
DROP TABLE IF EXISTS custom_link CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS recycle_link CASCADE;
DROP TABLE IF EXISTS aux_s_key CASCADE;